### PR TITLE
Option to wrap System.out and .err to Foundation.log (#216)

### PR DESCRIPTION
**Pull request by erwin1**
@ntherning I don't know if this is the most appropriate way of doing it (please advise if it isn't), but I've tried this out and I can know make system.out and err write to the Foundation.log using a system property.

### CODE REVIEW

**Comment by badlogic** [comment]
I think the FoundationLogPrintStream is a good idea, though i believe there needs to be some escaping of the String passed to `Founddation#log`, see https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Functions/#//apple_ref/c/func/NSLog. Maybe @BlueRiverInteractive has some input on that.

My opinion on properties is usually to avoid them if possible. Calling `System#setErr` can be done on application startup by the user. Discoverability of the properties or the `FoundationLogPrintStream` class is the same for users. IMO, the less we do implicitely, the better.

If the properties stay, then we should probably use `Boolean#parseBoolean` instead of the less robust String equals.

**Comment by BlueRiverInteractive** [comment]
Looks good! A few comments:
1. Use `Foundation.log("%@", new NSString(st.toString));` to prevent app crashing from wrongly formatted log message strings.
2. I'm not sure about the system properties. An alternative would be an option in the robovm.xml, to enforce it by default or don't do anything. Personally I would prefer to use this print stream as the default for `System.out` and `System.err`, because I don't see a reason why a developer wouldn't want to see his log messages in the console and XCode. 
It would probably prevent one or another bug report of logging not working :)

**Comment by ntherning** [comment]
Looks good, nice work! As commented we need to make sure the string is escaped. Either do what Dominik ( @BlueRiverInteractive ) suggested or escape every `%` in the string (`%` -> `%%`).

I don't mind if this was installed by default when there's no console attached (i.e. not run by RoboVM). Don't know the best way to detect that though. Not sure that's possible ATM. But I guess we could set some environment variable in `IOSTarget`? Then we would auto install these streams if that env var isn't set.

**Comment by erwin1** [comment]
Thanks for the feedback. I've committed changes accordingly.

**Comment by ntherning** [comment]
Thanks! I will merge this and just do a few minor changes. The env var can be checked using `System.getenv()` which is a bit simpler. And I will change the name of the env var. I think it's more common to have upper case names. And we recently got a request about detecting whether a debugger is attached so I will rename the var to `ROBOVM_LAUNCH_MODE` and set it to either `release` or `debug`. The presence of this var means we're running under RoboVM and the value reflects whether it's a release launch or debug launch.

**Pull request merged**
