### PR TITLE
signing dynamic libraries on IPA generation

### PR DESCRIPTION
**Pull request by alexitelman**
This should fix issue #1062

### CODE REVIEW

**Comment by badlogic** [comment]
Thanks, this looks good. I'll merge it in a bit and start a snapshot build for you. I'll report back here.

**Comment by badlogic** [comment]
Sorry, one complication. In order to merge this, we'll need a CLA from you, see http://robovm.com/support/code-contributions/ That's so we can publish your contribution under the OSS license. If you can't do this for some reason i'll implement the fix myself

**Comment by alexitelman** [comment]
Cool. I sent it to hello(at)robovm.com
BTW, I couldn't compile the robovm-idea plugin, I couldn't find some projects in the pom.xml.. for example robovm-lm.
Do you have updated instructions for this?

**Comment by badlogic** [comment]
robovm-lm is a propriatery package, so you'll have to exclude it from the plugin.

Thanks for the PR, i merged it an have triggered a snapshot build. It should be ready for you to try in 30 minutes from now.

**Comment by badlogic** [comment]
The snapshot is complete, you can download it form http://download.robovm.org/

Let me know if this works for you so we can close this issue. Thanks for the contribution!

**Comment by badlogic** [comment]
The snapshot build it ready at http://download.robovm.org/

Let me know if this works so we can close issue #1062 

Thanks for the contribution!

**Comment by alexitelman** [comment]
Doesn't work yet...

ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'NT87EN6678.media.muvix.wave' for key 'application-identifier' in 'Payload/Muvix.app/Frameworks/myframework.framework/myframework' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."

**Comment by alexitelman** [comment]
application-identifier in the entitlements.plist of the framework should be 'TEAMID.framework-bundle-identifier' and not 'TEAMID.app-bundle-identifier'

**Pull request merged**
