### PR TITLE
Use robovm to create a static iOS library

### PR DESCRIPTION
**Pull request by wfrank2509**
I "patched" robovm based on the various sources/feedback on StackOverflow and the Google group so that it can be used to create static libraries additionally to the default full apps.

The main key is to link to the "new" bclib library instead bc in the app. All the functionality available today in the standard robovm (i.e. robovm compiler) is not changed.

There is still lot of room for improvement and some redundant code parts between the bc and bclib could be extracted to a common package. I basically just copied the bc package over to bclib and patched the main method as well as the rvmRun method in init.c plus some additional headers to make the initializers available.

I would be happy to get some feedback about this approach and maybe/hopefully contribute in this direction to provide this new feature to robovm.

Thanks,
Wolfgang

### CODE REVIEW

**Comment by corradio** [comment]
Is there any work on this part?

**Comment by badlogic** [comment]
There is, but it's not based on this patch. I'm afraid we can't give a
definite ETA for it, but we'd like to make it public some time this year.

**Comment by wfrank2509** [comment]
Hi ... actually I will update the patch to the latest robovm version within the next 1-2 weeks.

**Comment by wfrank2509** [comment]
I think afterwards it needs to be thought of a better way for the integration as it is very prototype like at the moment ... (but working ;-) )

**Comment by ntherning** [comment]
There's a prototype for generating dynamic libs from your Java classes and
dependencies. Using dynamic libs is supported and allowed by apple in iOS
8+ apps. We will hopefully be able to clean this up and merge it within the
next few weeks and provide this as an experimental/alpha feature in the
next release (end of May) or the release after that (end of June).

Once we dynamic lib support  static lib support should be straight forward.
The hard part with both is how to debug them. We haven't figured that out
yet.

The dynamic/static lib support will be based on standard JNI. We will not
expose the internals of RoboVM, none of the rvm* functions will be callable.

**Comment by wfrank2509** [comment]
This sounds great! I will be more than happy to try out the feature and provide Feedback.
Actually I would also prefer dynamic libs over a static libs! Would it be possible to just create a Cocoa framework to of a "java" lib?

My current "hack" also accessed "Java" via JNI ... it worked well in most cases but is/was buggy when I uses NSRunLoops and other NSThreads/Queues in "Java" as the JNI Context got messed up then (i.e. EAAccessory Bluetooth stuff with NSStreams). Debugging and fixing these issues was really too hard without diving into every detail ob the robovm implementation. 
My current setup is to use JNI just to start a local NanoHTTP Server (Java) and access the "Java" functionality via a small REST-like http interface and try not to cross "Java" and Objc boundaries other than using NSUrlRequests if possible.

 Looking forward to the next release! 

Keep up the great work!

**Comment by vinaysshenoy** [comment]
Is there anything happening on this front? We really need the capability for robovm to be able to generate a static library and adding this feature in anytime soon would be brilliant.

**Comment by ntherning** [comment]
We're working on adding support for dynamic library creation. We will not merge this PR. Thanks for taking the time to submit it though.

**Comment by wfrank2509** [comment]
Thanks Niklas! We are looking forward to the official solution. It would be great to know when we could give it a first try and/or even help with it.

**Pull request closed without merging**
